baseURL = ""
languageCode = "en-us"
title = "My Digital Garden"
copyright = "Haoyuehx ©"


[params]
  name = "HaoyuehxのBlog"
  description = "Programs are meant to be read by humans and only incidentally for computers to execute."
  initials = "Haoyue"
  googleAnalytics = ""

# config.toml 修改后
[[params.social]]
  name = "Bilibili"
  link = "https://space.bilibili.com/3494363854276671"
  icon = "fa-brands fa-bilibili" # fab -> fa-brands

    [[params.social]]
    name = "QQ" 
    link = "#"
    icon = "fa-brands fa-qq" # fab -> fa-brands

    [[params.social]]
    name = "Weixin" 
    link = "#"
    icon = "fa-brands fa-weixin" # fab -> fa-brands

    [[params.social]]
    name = "Telegram" 
    link = "https://t.me/haoyuehx"
    icon = "fa-brands fa-telegram" # fab -> fa-brands

    [[params.social]]
    name = "Mail" 
    link = "#"
    icon = "fa-solid fa-envelope" # fas -> fa-solid

    [[params.social]]
    name = "Twitter"
    link = "https://x.com/Haoyuehx"
    # 推荐使用新的 X 平台图标名 fa-x-twitter
    icon = "fa-brands fa-x-twitter" 

    [[params.social]]
    name = "Zhihu"
    link = "https://www.zhihu.com/people/4skcf3"
    icon = "fa-brands fa-zhihu" # fab -> fa-brands

    [[params.social]]
    name = "Github"
    link = "https://github.com/haoyuehx"
    icon = "fa-brands fa-github" # fab -> fa-brands


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
